<x-chatter-layout>
@php
    $formatMinutes = fn(int $minutes) => intdiv($minutes, 60).'h '.str_pad((string)($minutes % 60), 2, '0', STR_PAD_LEFT).'m';
@endphp
<div class="mx-auto max-w-7xl space-y-5 text-boss-ivory">
    @if(session('status'))<div class="rounded-md border border-emerald-400/25 bg-emerald-400/10 p-4 text-sm text-emerald-200">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="rounded-md border border-red-400/25 bg-red-400/10 p-4 text-sm text-red-200">{{ $errors->first() }}</div>@endif

    <div class="flex flex-wrap items-end justify-between gap-3"><div><p class="pd-kicker">{{ __('Working Hours') }}</p><h1 class="pd-heading mt-2 text-[clamp(2rem,4vw,3rem)]">{{ __('Time Tracker') }}</h1><p class="mt-2 text-sm text-boss-ivory/45">{{ __('Your time: :timezone - Payroll weeks use Europe/London', ['timezone'=>$tz]) }}</p></div></div>

    <section class="grid gap-5 lg:grid-cols-[minmax(0,1.25fr)_minmax(280px,0.75fr)]">
        <div x-data="{ baseWorkedSeconds: @js($activeWorkedSeconds), timerRunning: @js($activeTimerRunning), displaySeconds: @js($activeWorkedSeconds), timer: null, format(v){const s=Math.max(0,v);return String(Math.floor(s/3600)).padStart(2,'0')+':'+String(Math.floor((s%3600)/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')} }" x-init="timer=setInterval(()=>{ if (timerRunning) displaySeconds++ },1000)" class="rounded-md border border-white/[0.08] bg-white/[0.035] p-6 sm:p-8">
            <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-[0.66rem] uppercase tracking-[0.18em] text-boss-ivory/40">{{ $openShift ? ($activeBreak ? __('On break') : __('Active shift')) : __('Ready') }}</p><p class="mt-3 font-display text-4xl sm:text-5xl" x-text="{{ $openShift ? 'format(displaySeconds)' : '\'00:00:00\'' }}"></p>@if($openShift)<p class="mt-2 text-sm text-boss-ivory/45">{{ __('Clocked in :time', ['time'=>$openShift->clocked_in_at->timezone($tz)->format('D, j M - g:i A T')]) }}</p><p class="mt-1 text-xs text-boss-ivory/35">{{ __('Worked time excludes breaks and is recalculated from server records after refresh.') }}</p>@endif</div><span class="inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs {{ $openShift ? 'border-emerald-400/25 bg-emerald-400/10 text-emerald-200' : 'border-white/10 text-boss-ivory/45' }}"><span class="h-2 w-2 rounded-full {{ $openShift ? 'bg-emerald-400' : 'bg-white/25' }}"></span>{{ $openShift ? ($activeBreak ? __('On break') : __('Clocked in')) : __('Clocked out') }}</span></div>
            <div class="mt-8 grid gap-3 sm:grid-cols-2">
                @if(!$openShift)<form method="POST" action="{{ route('chatter.clock-in') }}">@csrf<button class="pd-btn-primary h-12 w-full">{{ __('Clock In') }}</button></form>@else
                    @if($activeBreak)<form method="POST" action="{{ route('chatter.breaks.end') }}">@csrf<button class="pd-btn-secondary h-12 w-full">{{ __('Resume Work') }}</button></form>@else<form method="POST" action="{{ route('chatter.breaks.start') }}">@csrf<button class="pd-btn-secondary h-12 w-full">{{ __('Start Break') }}</button></form>@endif
                    <form method="POST" action="{{ route('chatter.clock-out') }}">@csrf<button class="h-12 w-full rounded-md border border-red-400/30 bg-red-400/10 px-5 text-sm font-bold text-red-200 transition hover:bg-red-400/20">{{ __('Clock Out') }}</button></form>
                @endif
            </div>
        </div>
        <div class="grid grid-cols-2 gap-3">
            @foreach([[__('Today worked'),$formatMinutes($todayTotals['worked_minutes'])],[__('This week worked'),$formatMinutes($currentTimesheet->ordinary_minutes)],[__('This month worked'),$formatMinutes($monthTotals['worked_minutes'])],[__('Estimated pay'),'GBP '.number_format($currentTimesheet->gross_pay_pence/100,2)]] as [$label,$value])<div class="rounded-md border border-white/[0.08] bg-white/[0.035] p-4"><p class="text-[0.62rem] uppercase tracking-[0.14em] text-boss-ivory/35">{{ $label }}</p><p class="mt-3 font-display text-2xl">{{ $value }}</p></div>@endforeach
        </div>
    </section>

    <section class="rounded-md border border-white/[0.08] bg-white/[0.025] p-5"><div class="flex flex-wrap items-end justify-between gap-3"><div><p class="pd-kicker">{{ __('Current Week') }}</p><h2 class="mt-1 font-display text-2xl">{{ $currentTimesheet->period_start->format('j M') }} - {{ $currentTimesheet->period_end->format('j M Y') }}</h2></div><span class="rounded-full border border-white/10 px-3 py-1 text-xs text-boss-ivory/50">{{ $currentTimesheet->statusLabel() }}</span></div>
        <div class="mt-5 overflow-x-auto"><table class="pd-table min-w-[720px]"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Clock in') }}</th><th>{{ __('Clock out') }}</th><th>{{ __('Hours Worked') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@forelse($currentShifts as $shift)<tr><td>{{ $shift->clocked_in_at->timezone($tz)->format('D, j M') }}</td><td>{{ $shift->clocked_in_at->timezone($tz)->format('g:i A') }}</td><td>{{ $shift->clocked_out_at?->timezone($tz)->format('g:i A') ?? __('Active') }}</td><td>{{ $formatMinutes((int) $shift->getAttribute('worked_minutes')) }}</td><td>{{ $shift->isOpen() ? ($activeBreak && $openShift?->is($shift) ? __('On break') : __('In progress')) : __('Recorded') }}</td></tr>@empty<tr><td colspan="5" class="text-center text-boss-ivory/40">{{ __('No shifts recorded this week.') }}</td></tr>@endforelse</tbody></table></div>
    </section>

    <section class="rounded-md border border-white/[0.08] bg-white/[0.025] p-5"><p class="pd-kicker">{{ __('Timesheet History') }}</p><div class="mt-4 space-y-3">@foreach($timesheets as $sheet)<div class="flex flex-col gap-3 rounded-md border border-white/[0.07] bg-white/[0.025] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-semibold">{{ $sheet->period_start->format('j M') }} - {{ $sheet->period_end->format('j M Y') }}</p><p class="mt-1 text-xs text-boss-ivory/45">{{ $formatMinutes($sheet->ordinary_minutes) }} - GBP {{ number_format($sheet->gross_pay_pence/100,2) }} - {{ $sheet->statusLabel() }}</p></div><div class="flex flex-wrap gap-2">@if(in_array($sheet->status,[\App\Models\ChatterTimesheet::STATUS_DRAFT,\App\Models\ChatterTimesheet::STATUS_CHANGES_REQUESTED],true) && now(\App\Services\ChatterPayrollService::REPORTING_TIMEZONE)->startOfDay()->gt($sheet->period_end))<form method="POST" action="{{ route('chatter.timesheets.submit',$sheet) }}">@csrf<button class="pd-btn-primary h-9">{{ __('Submit') }}</button></form>@endif @if(in_array($sheet->status,[\App\Models\ChatterTimesheet::STATUS_SUBMITTED,\App\Models\ChatterTimesheet::STATUS_APPROVED],true))<form method="POST" action="{{ route('chatter.timesheets.correction',$sheet) }}" class="flex gap-2"><input name="reason" class="pd-input h-9 min-w-0" placeholder="{{ __('Correction reason') }}" required><button class="pd-btn-secondary h-9">{{ __('Request') }}</button></form>@endif</div></div>@endforeach</div>@if($timesheets->hasPages())<div class="mt-5">{{ $timesheets->links() }}</div>@endif</section>
</div>
</x-chatter-layout>
