[program:paradisedollz-scheduler]
command=php /var/www/paradisedollz/artisan schedule:work --no-ansi
directory=/var/www/paradisedollz
autostart=true
autorestart=true
stopwaitsecs=30
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/paradisedollz-scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
